### ISSUE TITLE
Add support for nested types

### ISSUE THREAD

**Issue by jorgecarleitao** [DataEngineeringLabs/arrow2-derive#2]
I.e. given two derived structs `Foo` and `Bar` on which `Foo` uses `Bar`, `Foo`'s schema should use `Bar`'s schema to be derived.

**Comment by ncpenke** [comment]
HI @jorgecarleitao great work with arrow2. I wanted to use it with my existing structures so I ended up modifying this crate to add support for nested structs, nested lists, and custom types.

I followed a serde-like trait-based approach, but did not use serde itself.

If you're interested in taking a look, here's a modification of your [example](https://github.com/ncpenke/arrow2-derive/blob/c6241d228b652177b834608104d9ac860c7f912a/tests/complex_example.rs).

I may missed some of the conventions, and the code probably needs a lot of cleanup and documentation. If you think this functionality will be useful either in this crate, or elsewhere I'd be happy to incorporate the appropriate feedback, and integrate or publish it. Thanks!

**Comment by jorgecarleitao** [comment]
I went through it and it looks freaking awesome!! Amazing work, @ncpenke !

Let me know what you prefer. For now, I invite you to have access to this repo. :)

One idea would be to PR and merge it here so that we can work on it together here and publish this to arrow2-derive in crates.io.

**Comment by ncpenke** [comment]
Thank you @jorgecarleitao, working on this together would be awesome!

Here's PR https://github.com/DataEngineeringLabs/arrow2-derive/pull/10. I'll push one more commit to the PR to update the README/docs, and to tweak the top-level API. 

I'll also open tickets for some remaining work (union, testing, i64 offset, etc).

**Comment by jorgecarleitao** [comment]
Closed by #10
