### ISSUE TITLE
Renaming crates before publishing?

### ISSUE THREAD

**Issue by ncpenke** [DataEngineeringLabs/arrow2-derive#20]
One thing that stands out is that we have two crates: arrow2_derive, and derive_internals, both both need to be published. 

If we were to follow the typical convention, the derive_internals crate should actually be arrow2_derive, and the current arrow2_derive, which contains the recently added traits should be called something else, perhaps arrow2_convert? 

There is some additional functionality that could go into arrow2_convert that provide additional helper API that's higher-level than what the arrow2 crate provides.

@jorgecarleitao thoughts?

**Comment by jorgecarleitao** [comment]
Good point. We need two crates because of some pro-macro thing, right? 

You mean the typical convention as in https://docs.rs/serde_derive/latest/serde_derive/ that just offers the macros, right?

If yes, I agree with you :), and the naming sounds great also!

**Comment by ncpenke** [comment]
One more though, since the naming convention seems to be * and *_derive, we should probably call the derive crate arrow2_convert_derive. If that reasoning makes sense, it would probably merit changing the repository name to arrow2_convert at some point to follow convention. I think we can hold off until things are in a state where we can publish.
